export interface AIMessage {
  id: string
  role: "user" | "assistant"
  content: string
  timestamp: Date
}

export interface StudentContext {
  studentName: string
  dominantLearningStyle: string
  secondaryStyle?: string
  currentTopic: string
  masteryLevel: number
}

// Mock AI responses based on learning style
import buildTutorPrompt from "./ai/promptBuilder"

export function generateAIResponse(userQuery: string, context: StudentContext): string {
  const { dominantLearningStyle, currentTopic, masteryLevel } = context

  // Enforce dominant learning style: normalize to lowercase expected by
  // `buildTutorPrompt` and downstream systems. We will ignore any user
  // requests to "switch" style in the query to ensure consistent tutoring
  // behavior (prevent manual style switching inside the chat).
  const dominantStyleKey = (dominantLearningStyle || "visual").toString().toLowerCase()

  // Sanitize the user query to remove explicit style-switching phrases so the
  // assistant does not change presentation style on demand. This is a simple
  // safeguard (removes standalone style words); the prompt builder also
  // instructs the model to stick to the grade-level syllabus and the given
  // style, which reduces hallucination and style drift.
  const sanitizedQuery = userQuery.replace(/\b(visual|auditory|reading|kinesthetic)\b/gi, "")

  // Build a constrained prompt for the AI tutor. `grade` is not available in
  // the StudentContext for the demo so we default to Grade 7; this anchors
  // the response depth to a syllabus-level and helps prevent the model from
  // producing out-of-scope material. If you have grade-level data, pass it
  // into StudentContext and surface it here instead.
  const grade = 7
  const prompt = buildTutorPrompt(grade, currentTopic, masteryLevel, dominantStyleKey as any, sanitizedQuery)

  // Map learning styles to response strategies (mock implementations).
  // Responses are generated using the dominant style and mastery level so
  // they follow the prompt's instructions about depth and presentation.
  const responseStrategies: Record<
    string,
    (query: string, topic: string, mastery: number, secondary?: string) => string
  > = {
    visual: generateVisualResponse,
    auditory: generateAuditoryResponse,
    reading: generateReadingResponse,
    kinesthetic: generateKinestheticResponse,
  }

  const generateResponse = responseStrategies[dominantStyleKey] || generateVisualResponse

  // Here we return a mock response generated by the style-specific helper.
  // In a production integration this `prompt` would be sent to the LLM API
  // (e.g., via fetch) to get a model-generated reply that follows the exact
  // prompt constraints. Keeping the mock generator ensures deterministic
  // behavior for local development.
  const modelReply = generateResponse(sanitizedQuery, currentTopic, masteryLevel, context.secondaryStyle)

  // For debugging and transparency, we can prefix the reply with the prompt
  // used to generate it (commented out in UI). We do not include the full
  // prompt in the returned string to keep the chat clean.
  // return `PROMPT:\n${prompt}\n\nREPLY:\n${modelReply}`

  return modelReply
}

function generateVisualResponse(query: string, topic: string, masteryLevel: number, secondary?: string): string {
  const responses = {
    default: `Let me visualize that for you!

For "${topic}", here's a visual breakdown:

[Visual Diagram]
Step 1 → Understanding basics
Step 2 → Applying concepts  
Step 3 → Complex applications

Your current mastery level (${masteryLevel}%) means you should focus on Step ${Math.floor(masteryLevel / 30) + 1}.

Key visual elements to remember:
• Use color-coding for different concepts
• Draw diagrams to visualize relationships
• Create mind maps for complex topics${secondary ? `\n\nYour secondary ${secondary} learning style also helps when you need to explain concepts verbally or apply them practically!` : ""}`,

    explanation: `Great question! Let me break this down visually.

The key concept here is that visual learners benefit from seeing patterns and relationships. For "${topic}":

🔵 Concept A → 🟢 Concept B → 🟡 Concept C

As you progress through your learning (currently at ${masteryLevel}% mastery), you'll start to see how these connect.

Try creating a visual representation of what you're learning!`,
  }

  return responses.explanation
}

function generateAuditoryResponse(query: string, topic: string, masteryLevel: number, secondary?: string): string {
  return `Excellent question! Let me explain "${topic}" in a way that works for auditory learners.

Think of it this way: imagine you're explaining this to a friend out loud. 

The main idea is: [Core concept explanation]
First, you'd say: "${topic} starts with understanding..."
Then you build on it: "Once you understand that, the next layer is..."
Finally, you connect it: "And that's how it all fits together!"

Your current mastery level is ${masteryLevel}%, which means you're at a good foundation.

Key tips for auditory learners:
• Try saying concepts out loud
• Listen to explanations (podcasts, videos with narration)
• Discuss with peers to reinforce learning${secondary ? `\n\nYour secondary ${secondary} learning style can also help by providing visual or hands-on reinforcement!` : ""}`
}

function generateReadingResponse(query: string, topic: string, masteryLevel: number, secondary?: string): string {
  return `Excellent question! Here's a comprehensive text-based explanation of "${topic}".

DEFINITION:
"${topic}" is fundamentally about understanding and applying core principles.

KEY CONCEPTS:
1. Foundation: The basic building blocks
2. Application: How to use these concepts
3. Analysis: Understanding deeper relationships
4. Synthesis: Combining concepts in new ways

PROGRESSION GUIDE:
At ${masteryLevel}% mastery, you've covered:
✓ Foundation concepts
${masteryLevel > 50 ? "✓ Basic applications" : "→ Next: Basic applications"}
${masteryLevel > 75 ? "✓ Advanced analysis" : "→ Future: Advanced analysis"}

RECOMMENDED READING:
• Start with fundamental texts
• Move to intermediate complexity
• Progress to advanced resources

Continue building your understanding through structured reading!${secondary ? `\n\nYour secondary ${secondary} learning style can help by providing visual diagrams or practical exercises!` : ""}`
}

function generateKinestheticResponse(query: string, topic: string, masteryLevel: number, secondary?: string): string {
  return `Perfect! Let me give you hands-on practice steps for "${topic}".

STEP-BY-STEP PRACTICE:

Step 1 (Foundation): Try this simple exercise
- Take action on the basic concept
- Practice until comfortable
- Current mastery: ${masteryLevel}%

Step 2 (Intermediate): Apply what you learned
- Work through a more complex problem
- Connect multiple concepts
- Adjust your approach based on results

Step 3 (Advanced): Create your own application
- Design a novel solution
- Test your understanding
- Refine based on outcomes

HANDS-ON TIPS FOR "${topic}":
• Use manipulatives or models
• Practice with real-world examples
• Learn by doing, not just watching
• Make mistakes and learn from them

What specific practice problem would you like to work through?${secondary ? `\n\nYour secondary ${secondary} learning style can help by providing theoretical explanations or visualizations!` : ""}`
}

export function generateContentRecommendations(studentProfile: {
  masteryScores: Record<string, number>
  dominantStyle: string
  engagementLevel: number
}): Array<{ title: string; reason: string; priority: "high" | "medium" | "low" }> {
  const recommendations = []

  const lowMasteryTopics = Object.entries(studentProfile.masteryScores)
    .filter(([_, score]) => score < 60)
    .sort((a, b) => a[1] - b[1])

  if (lowMasteryTopics.length > 0) {
    const [topic, score] = lowMasteryTopics[0]
    recommendations.push({
      title: `Master "${topic}" (Currently ${score}%)`,
      reason: `You're struggling with this concept. We recommend ${studentProfile.dominantStyle.toLowerCase()}-focused content.`,
      priority: "high",
    })
  }

  const almostMastered = Object.entries(studentProfile.masteryScores)
    .filter(([_, score]) => score >= 70 && score < 80)
    .sort((a, b) => b[1] - a[1])

  if (almostMastered.length > 0) {
    const [topic, score] = almostMastered[0]
    recommendations.push({
      title: `Polish "${topic}" to Mastery (+${100 - score}% needed)`,
      reason: "You're close! A few more practice problems will get you to mastery.",
      priority: "high",
    })
  }

  if (studentProfile.engagementLevel > 70) {
    const masteredTopics = Object.entries(studentProfile.masteryScores).filter(([_, score]) => score >= 80).length

    recommendations.push({
      title: `Challenge: Explore Advanced Topics`,
      reason: "You're highly engaged and have mastered several topics. Ready to explore advanced content?",
      priority: "medium",
    })
  }

  return recommendations.slice(0, 3)
}
