export interface ProgressSnapshotInput {
  studentName: string
  parentName?: string
  parentEmail?: string
  overallMastery: number
  engagementLevel: number
  dominantStyle?: string
  masteryByTopic: Array<{ topicName: string; score: number }>
  badges?: Array<{ name: string }>
  recentActivity?: Array<{ description: string; timestamp: string }>
}

export interface ProgressSnapshot {
  subject: string
  headline: string
  summary: string
  strengths: string[]
  focusAreas: string[]
  highlights: string[]
  textBody: string
  htmlBody: string
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date)
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

export function buildWeeklyProgressSnapshot(input: ProgressSnapshotInput): ProgressSnapshot {
  const studentName = input.studentName?.trim() || "Your child"
  const today = new Date()
  const weekAgo = new Date(today)
  weekAgo.setDate(today.getDate() - 7)

  const strongestTopics = [...input.masteryByTopic].sort((a, b) => b.score - a.score).slice(0, 3)
  const focusTopics = [...input.masteryByTopic].sort((a, b) => a.score - b.score).slice(0, 3)
  const badgeNames = (input.badges || []).slice(0, 3).map((badge) => badge.name)
  const recentMoments = (input.recentActivity || [])
    .slice(0, 3)
    .map((activity) => `${activity.description} (${formatDate(new Date(activity.timestamp))})`)

  const strengths =
    strongestTopics.length > 0
      ? strongestTopics.map((topic) => `${topic.topicName}: ${Math.round(topic.score)}% mastery`)
      : ["No scored topics yet, but the student has started building progress this week."]

  const focusAreas =
    focusTopics.length > 0
      ? focusTopics.map((topic) => `${topic.topicName}: ${Math.round(topic.score)}% mastery`)
      : ["Continue completing modules to unlock detailed topic feedback."]

  const highlights = [
    `Overall mastery is ${Math.round(input.overallMastery)}%.`,
    `Engagement is ${Math.round(input.engagementLevel)}%.`,
    input.dominantStyle ? `Preferred learning style: ${input.dominantStyle}.` : "Learning style profile is still being refined.",
    ...(badgeNames.length > 0 ? [`Recent badges: ${badgeNames.join(", ")}.`] : []),
    ...(recentMoments.length > 0 ? [`Recent activity: ${recentMoments.join(" | ")}.`] : []),
  ]

  const headline = `${studentName}'s weekly mastery snapshot`
  const summary = `${studentName} is tracking at ${Math.round(input.overallMastery)}% mastery with ${Math.round(input.engagementLevel)}% engagement from ${formatDate(weekAgo)} to ${formatDate(today)}.`
  const subject = `AMEP Weekly Snapshot for ${studentName}`

  const textBody = [
    `Hello ${input.parentName || "Parent/Guardian"},`,
    "",
    `Here is this week's Adaptive Mastery & Engagement Platform snapshot for ${studentName}.`,
    "",
    `Summary: ${summary}`,
    "",
    "Top strengths:",
    ...strengths.map((item) => `- ${item}`),
    "",
    "Focus areas:",
    ...focusAreas.map((item) => `- ${item}`),
    "",
    "Highlights:",
    ...highlights.map((item) => `- ${item}`),
    "",
    "Thank you for supporting consistent, personalized learning.",
    "",
    "Generated by AMEP",
  ].join("\n")

  const htmlBody = `
    <div style="font-family:Arial,sans-serif;line-height:1.5;color:#0f172a;">
      <h2 style="margin-bottom:8px;">${escapeHtml(headline)}</h2>
      <p style="margin:0 0 16px;">${escapeHtml(summary)}</p>
      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-bottom:20px;">
        <div style="padding:12px;border:1px solid #cbd5e1;border-radius:12px;background:#eff6ff;">
          <strong>Mastery</strong>
          <div style="font-size:24px;margin-top:4px;">${Math.round(input.overallMastery)}%</div>
        </div>
        <div style="padding:12px;border:1px solid #cbd5e1;border-radius:12px;background:#ecfeff;">
          <strong>Engagement</strong>
          <div style="font-size:24px;margin-top:4px;">${Math.round(input.engagementLevel)}%</div>
        </div>
        <div style="padding:12px;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc;">
          <strong>Learning Style</strong>
          <div style="font-size:20px;margin-top:4px;">${escapeHtml(input.dominantStyle || "In progress")}</div>
        </div>
      </div>
      <h3>Top strengths</h3>
      <ul>${strengths.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
      <h3>Focus areas</h3>
      <ul>${focusAreas.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
      <h3>Highlights</h3>
      <ul>${highlights.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
    </div>
  `.trim()

  return {
    subject,
    headline,
    summary,
    strengths,
    focusAreas,
    highlights,
    textBody,
    htmlBody,
  }
}

export function buildMailtoUrl(to: string, subject: string, body: string) {
  const params = new URLSearchParams({
    subject,
    body,
  })
  return `mailto:${encodeURIComponent(to)}?${params.toString()}`
}
